### ISSUE TITLE
Quick TODO before launch

### ISSUE THREAD

**Issue by Cannonb4ll** [ploi-deploy/heatmap#2]
- [x] Fix iFrame navigating updating livewire's state and loading new clicks
- [x] Fix iFrame scaling upon XL or XXL (will be separate issue)
- [x] Fix button states for screen sizes when pressing them
- [x] Add filter for date (defaults to today) (top right)
- [x] Purge clicks (with date filter)
- [x] Add NGINX x-frame example to readme
